name: cache-test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: prime-cache-612e66a
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-612e66a

      - name: prime-cache-612e66a
        run: echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
